# Generated by Django 4.1.2 on 2023-01-10 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0014_alter_overview_deceased_name'),
        ('users', '0002_alter_tasklistener_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='order',
        ),
        migrations.AddField(
            model_name='usertask',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='orders.orderitem'),
        ),
        migrations.AlterField(
            model_name='usertask',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
