# Generated by Django 4.1.2 on 2023-01-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_is_deleted'),
        ('users', '0003_remove_usertask_order_usertask_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='task',
        ),
        migrations.AddField(
            model_name='usertask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to='tasks.task'),
        ),
    ]
