# Generated by Django 4.1.2 on 2023-01-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_usertask_task_usertask_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='assigned_on',
            new_name='started_on',
        ),
    ]
