# Generated by Django 4.1.2 on 2023-01-13 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_rename_assigned_on_usertask_started_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=512)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.usertask')),
            ],
        ),
    ]
