# Generated by Django 4.1.2 on 2023-04-13 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_1', models.TextField(blank=True, null=True)),
                ('placement_2', models.TextField(blank=True, null=True)),
                ('placement_3', models.TextField(blank=True, null=True)),
                ('placement_4', models.TextField(blank=True, null=True)),
                ('placement_5', models.TextField(blank=True, null=True)),
                ('placement_6', models.TextField(blank=True, null=True)),
                ('placement_7', models.TextField(blank=True, null=True)),
                ('placement_8', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemorialPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memorial_placement', models.IntegerField()),
                ('section', models.CharField(max_length=255)),
                ('lot', models.CharField(max_length=255)),
                ('grave', models.CharField(max_length=255)),
                ('face_stone', models.CharField(max_length=255)),
                ('foundation_length', models.CharField(max_length=255)),
                ('foundation_width', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('placement_names', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.placementnames')),
            ],
        ),
    ]
