# Generated by Django 4.1.2 on 2023-04-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_placementnames_memorialplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorialplacement',
            name='memorial_placement',
            field=models.IntegerField(default=1),
        ),
    ]
