# Generated by Django 4.1.2 on 2023-04-13 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_memorialplacement_memorial_placement'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='placement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.memorialplacement'),
        ),
        migrations.AlterField(
            model_name='memorialplacement',
            name='face_stone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memorialplacement',
            name='foundation_length',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memorialplacement',
            name='foundation_width',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memorialplacement',
            name='grave',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memorialplacement',
            name='lot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memorialplacement',
            name='section',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
