# Generated by Django 4.1.2 on 2023-04-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_placement_alter_memorialplacement_face_stone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorialplacement',
            name='read_top',
            field=models.BooleanField(default=True),
        ),
    ]
