# Generated by Django 4.1.2 on 2023-04-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_memorialplacement_read_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memorialplacement',
            name='face_stone',
            field=models.CharField(default='Unspecified', max_length=255),
        ),
    ]
