# Generated by Django 4.1.2 on 2022-11-25 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contactable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cemetery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=256)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contactable.contact')),
            ],
        ),
    ]
