# Generated by Django 4.1.2 on 2022-12-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_itemoption_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogeditem',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
