# Generated by Django 4.2.3 on 2023-07-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='triggers_after',
            field=models.ManyToManyField(blank=True, to='tasks.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='triggers_at_all_tasks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='triggers_at_beginning',
            field=models.BooleanField(default=False),
        ),
    ]
