# Generated by Django 4.1.2 on 2022-10-28 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120)),
                ('allow_null', models.BooleanField()),
                ('allow_multi', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemOptionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('subtext', models.CharField(max_length=120)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='items.itemoption')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=120)),
                ('sub_type', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('commissionable', models.BooleanField()),
                ('tax_exempt', models.BooleanField()),
                ('sizeable', models.BooleanField()),
                ('options', models.ManyToManyField(to='items.itemoption')),
            ],
        ),
    ]
