# Generated by Django 4.1.2 on 2022-11-08 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemoptionvalue',
            name='title',
        ),
    ]
