# Generated by Django 4.1.2 on 2022-12-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_catalogeditem_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogeditem',
            name='tax_exempt',
        ),
    ]
