# Generated by Django 4.1.2 on 2022-12-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_catalogeditem_tax_exempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoptionvalue',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
