# Generated by Django 4.1.2 on 2022-12-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_itemoptionvalue_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoption',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
