# Generated by Django 4.1.2 on 2022-11-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('organization', models.CharField(blank=True, max_length=128)),
                ('email', models.CharField(blank=True, max_length=128)),
                ('phone_number', models.CharField(blank=True, max_length=128)),
                ('fax_number', models.CharField(blank=True, max_length=128)),
                ('website', models.CharField(blank=True, max_length=256)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
