# Generated by Django 4.1.2 on 2022-12-12 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0004_remove_catalogeditem_tax_exempt'),
        ('contactable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=40)),
                ('order_type', models.CharField(max_length=40)),
                ('promise_date', models.DateField()),
                ('reference_tag', models.CharField(max_length=40)),
                ('tax_exempt', models.BooleanField()),
                ('delivery_method', models.CharField(max_length=40)),
                ('customer_contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contactable.contact')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('notes', models.TextField()),
                ('tax_exempt', models.BooleanField()),
                ('cataloged_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.catalogeditem')),
                ('item_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.itemset')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_set', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.itemset')),
            ],
        ),
    ]
