# Generated by Django 4.1.2 on 2022-12-12 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_catalogeditem_tax_exempt'),
        ('orders', '0002_order_order_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='items.itemoption')),
            ],
        ),
        migrations.CreateModel(
            name='ItemSpecificationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vector3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='ItemSpecifications',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cataloged_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.catalogeditem'),
        ),
        migrations.AddField(
            model_name='itemspecification',
            name='specification_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='orders.itemspecificationset'),
        ),
        migrations.AddField(
            model_name='itemspecification',
            name='values',
            field=models.ManyToManyField(to='items.itemoptionvalue'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dimensions',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.vector3'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='specifications',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.itemspecificationset'),
        ),
    ]
