# Generated by Django 4.1.2 on 2022-12-12 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_itemspecification_itemspecificationset_vector3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='specifications',
            new_name='specification_set',
        ),
    ]
