# Generated by Django 4.1.2 on 2022-12-21 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitem_cataloged_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=128)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=128)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='overview',
            name='reference_tag',
        ),
        migrations.AlterField(
            model_name='overview',
            name='status',
            field=models.CharField(choices=[('Quote', 'Quote'), ('Hold/Layaway', 'Hold Layaway'), ('Active', 'Active'), ('Cancelled', 'Cancelled'), ('Pre-Need', 'Pre Need'), ('Completed', 'Completed')], default='Quote', max_length=15),
        ),
        migrations.AlterField(
            model_name='overview',
            name='delivery_method',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.deliverymethod'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='order_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ordertype'),
        ),
    ]
