# Generated by Django 4.1.2 on 2022-12-21 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_deliverymethod_ordertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='overview',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.overview'),
        ),
    ]
