# Generated by Django 4.1.2 on 2022-12-21 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactable', '0001_initial'),
        ('orders', '0008_order_overview'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='overview',
            name='customer_contact',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contactable.contact'),
        ),
        migrations.AlterField(
            model_name='overview',
            name='promise_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='overview',
            name='tax_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
