# Generated by Django 4.1.2 on 2022-12-21 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactable', '0001_initial'),
        ('orders', '0009_order_is_deleted_alter_overview_customer_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='customer_contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contactable.contact'),
        ),
    ]
