# Generated by Django 4.1.2 on 2022-12-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_overview_cemetery'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
