# Generated by Django 4.1.2 on 2023-01-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_overview_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='deceased_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='overview',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Active', 'Active'), ('Production Hold', 'Production Hold'), ('Ready To Invoice', 'Ready To Invoice'), ('Invoiced', 'Invoiced'), ('Paid', 'Paid')], default='Active', max_length=16),
        ),
    ]
