# Generated by Django 4.1.2 on 2023-01-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_overview_deceased_name_alter_overview_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overview',
            name='deceased_name',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
