# Generated by Django 4.2.3 on 2023-07-28 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_cataloged_items', models.BooleanField(default=False)),
                ('can_edit_cataloged_items', models.BooleanField(default=False)),
                ('can_delete_cataloged_items', models.BooleanField(default=False)),
                ('can_view_cataloged_items', models.BooleanField(default=True)),
                ('can_create_cataloged_tasks', models.BooleanField(default=False)),
                ('can_edit_cataloged_tasks', models.BooleanField(default=False)),
                ('can_delete_cataloged_tasks', models.BooleanField(default=False)),
                ('can_view_cataloged_tasks', models.BooleanField(default=True)),
                ('can_create_addresses', models.BooleanField(default=False)),
                ('can_edit_addresses', models.BooleanField(default=False)),
                ('can_delete_addresses', models.BooleanField(default=False)),
                ('can_view_addresses', models.BooleanField(default=True)),
                ('can_create_orders', models.BooleanField(default=False)),
                ('can_edit_orders', models.BooleanField(default=False)),
                ('can_view_orders', models.BooleanField(default=False)),
                ('can_force_start_tasks', models.BooleanField(default=False)),
                ('can_upload_documents', models.BooleanField(default=False)),
                ('can_make_tasks_comments', models.BooleanField(default=False)),
                ('can_mark_foreign_task_complete', models.BooleanField(default=False)),
                ('can_create_order_items', models.BooleanField(default=False)),
                ('can_edit_order_items', models.BooleanField(default=False)),
                ('can_view_order_financials', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_create_users', models.BooleanField(default=False)),
                ('can_edit_users', models.BooleanField(default=False)),
                ('can_delete_users', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
